// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMqPuWLRmOzm0DvIqh18KhL-VH1zAtVQ',
    appId: '1:1025594635759:web:82e5950e6eeb5de937f21a',
    messagingSenderId: '1025594635759',
    projectId: 'umuziki-e2448',
    authDomain: 'umuziki-e2448.firebaseapp.com',
    storageBucket: 'umuziki-e2448.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3ezoioT82eVAjN-9ZvFPSu3hG98aYYE',
    appId: '1:1025594635759:android:76a3b62b8a7216c137f21a',
    messagingSenderId: '1025594635759',
    projectId: 'umuziki-e2448',
    storageBucket: 'umuziki-e2448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC389zvf9n3Pqi-KkZ9Ttpk6ENHSqkdMSE',
    appId: '1:1025594635759:ios:9a6137ec15d3d17037f21a',
    messagingSenderId: '1025594635759',
    projectId: 'umuziki-e2448',
    storageBucket: 'umuziki-e2448.firebasestorage.app',
    iosClientId: '1025594635759-gj540lftv20qloghs38ml3fp74bopgmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC389zvf9n3Pqi-KkZ9Ttpk6ENHSqkdMSE',
    appId: '1:1025594635759:ios:9a6137ec15d3d17037f21a',
    messagingSenderId: '1025594635759',
    projectId: 'umuziki-e2448',
    storageBucket: 'umuziki-e2448.firebasestorage.app',
    iosClientId: '1025594635759-gj540lftv20qloghs38ml3fp74bopgmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoMqPuWLRmOzm0DvIqh18KhL-VH1zAtVQ',
    appId: '1:1025594635759:web:bb4cd93b8021f55a37f21a',
    messagingSenderId: '1025594635759',
    projectId: 'umuziki-e2448',
    authDomain: 'umuziki-e2448.firebaseapp.com',
    storageBucket: 'umuziki-e2448.firebasestorage.app',
  );

}